/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Business.Resume;
import Business.ResumeHistory;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author leslie
 */
public class CreatePanel extends javax.swing.JPanel {
    
    JFileChooser chooser = new JFileChooser();
    private ImageIcon pht1;
    private ResumeHistory resumeHistory;

    public CreatePanel(ResumeHistory resumeHistory) {
        initComponents();
        this.resumeHistory = resumeHistory;
    }
    
    public boolean validDate(String m1, String y1, String m2, String y2)
    {
        int M1 = Integer.parseInt(m1);
        int Y1 = Integer.parseInt(y1);
        int M2 = Integer.parseInt(m2);
        int Y2 = Integer.parseInt(y2);
        
        if ((Y2 > Y1 ||(Y2 == Y1 && M2 > M1))
                && M1 >= 1
                && M1 <= 12
                && Y1 <= 2016
                && Y1 >= 1916
                && M2 >= 1
                && M2 <= 12
                && Y2 >= 1916
                && Y2 <= 2016) {
            return true;
        } else { 
            JOptionPane.showMessageDialog(null, "Date Illegal, Please check.");
            return false;
        }
            
    }

    
    //if firstname and lastname text field both filled, return true
    public boolean validName(String str){
        if (str == null || str.length() <= 0) {
            JOptionPane.showMessageDialog(null, "Please fill your firstname and your lastname.");
            return false;
        }
        else return true;
    }
    
    public boolean validphone(String str){
        boolean isNum =false;
        for (int i = str.length();--i>=0;){  
            if (!Character.isDigit(str.charAt(i))){
            isNum = false;
            break;
            }
        isNum = true;
        }
        if (isNum && str.length()==10) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Please fill a valid USA phone number");
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGrp = new javax.swing.ButtonGroup();
        nationalityBtnGroup = new javax.swing.ButtonGroup();
        statusBtnGroup = new javax.swing.ButtonGroup();
        createScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        lNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        streetln1TextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        collegeNameTextField = new javax.swing.JTextField();
        specialtyTextField = new javax.swing.JTextField();
        gpaTextField = new javax.swing.JTextField();
        eduDateFromMTextField = new javax.swing.JTextField();
        eduDateToMTextField = new javax.swing.JTextField();
        eduDateFromYTextField = new javax.swing.JTextField();
        eduDateToYTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pj1DateFromMTextField = new javax.swing.JTextField();
        pj1DateToMTextField = new javax.swing.JTextField();
        pj1DateFromYTextField = new javax.swing.JTextField();
        pj1DateToYTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pj1TextArea = new javax.swing.JTextArea();
        pj2DateFromMTextField = new javax.swing.JTextField();
        pj2DateToMTextField = new javax.swing.JTextField();
        pj2DateFromYTextField = new javax.swing.JTextField();
        pj2DateToYTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pj2TextArea = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objStatementTextArea = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        languagesTextField = new javax.swing.JTextField();
        certificatesTextField = new javax.swing.JTextField();
        hobbiesTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        chooseBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        maleRBtn = new javax.swing.JRadioButton();
        femaleRBtn = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ctzRBtn = new javax.swing.JRadioButton();
        internationalRBtn = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        grduatedRBtn = new javax.swing.JRadioButton();
        inProcessRBtn = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        cplusCBox = new javax.swing.JCheckBox();
        javaCBox = new javax.swing.JCheckBox();
        pythonCBox = new javax.swing.JCheckBox();
        cCBox = new javax.swing.JCheckBox();
        phpCBox = new javax.swing.JCheckBox();
        jsCBox = new javax.swing.JCheckBox();
        htmlCBox = new javax.swing.JCheckBox();
        tcpCBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(240, 247, 237));

        createScrollPane.setBackground(new java.awt.Color(240, 247, 237));
        createScrollPane.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(240, 247, 237));

        jLabel1.setFont(new java.awt.Font("Savoye LET", 1, 36)); // NOI18N
        jLabel1.setText("Create a Resume");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("BASIC INFORMATION");

        jLabel5.setText("Street Line 1:");

        fNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Street Line 2:");

        jLabel7.setText("City:");

        jLabel8.setText("Country:");

        jLabel9.setText("Phone:");

        jLabel10.setText("Affiliation:");

        phoneTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        affiliationTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        streetln1TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        streetln2TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cityTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        countryTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("EDUCATION ");

        jLabel12.setText("Date:");

        jLabel13.setText("From");

        jLabel14.setText("To");

        jLabel15.setText("College Name:");

        jLabel16.setText("Specialty:");

        jLabel17.setText("GPA:");

        collegeNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        specialtyTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gpaTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        eduDateFromMTextField.setText("01");
        eduDateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateFromMTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromMTextFieldActionPerformed(evt);
            }
        });

        eduDateToMTextField.setText("02");
        eduDateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateToMTextField.setFocusTraversalKeysEnabled(false);
        eduDateToMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateToMTextFieldActionPerformed(evt);
            }
        });

        eduDateFromYTextField.setText("2000");
        eduDateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateFromYTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromYTextFieldActionPerformed(evt);
            }
        });

        eduDateToYTextField.setText("2001");
        eduDateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("PROJECTS AND INTERNSHIPS");

        pj1DateFromMTextField.setText("03");
        pj1DateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateFromMTextField.setFocusTraversalKeysEnabled(false);

        pj1DateToMTextField.setText("04");
        pj1DateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateToMTextField.setFocusTraversalKeysEnabled(false);

        pj1DateFromYTextField.setText("2000");
        pj1DateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateFromYTextField.setFocusTraversalKeysEnabled(false);
        pj1DateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj1DateFromYTextFieldActionPerformed(evt);
            }
        });

        pj1DateToYTextField.setText("2001");
        pj1DateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel19.setText("Date:");

        jLabel20.setText("From");

        jLabel21.setText("To");

        jLabel22.setText("Description:");

        pj1TextArea.setColumns(20);
        pj1TextArea.setRows(5);
        jScrollPane1.setViewportView(pj1TextArea);
        pj1TextArea.setLineWrap(true);
        pj1TextArea.setWrapStyleWord(true);

        pj2DateFromMTextField.setText("05");
        pj2DateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pj2DateToMTextField.setText("06");
        pj2DateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj2DateToMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj2DateToMTextFieldActionPerformed(evt);
            }
        });

        pj2DateFromYTextField.setText("2004");
        pj2DateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj2DateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj2DateFromYTextFieldActionPerformed(evt);
            }
        });

        pj2DateToYTextField.setText("2016");
        pj2DateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setText("Date:");

        jLabel24.setText("From");

        jLabel25.setText("To");

        jLabel26.setText("Description:");

        pj2TextArea.setColumns(20);
        pj2TextArea.setRows(5);
        jScrollPane2.setViewportView(pj2TextArea);
        pj2TextArea.setLineWrap(true);
        pj2TextArea.setWrapStyleWord(true);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("CAREER OBJECTIVE STATEMENT");

        jLabel29.setText("Description:");

        objStatementTextArea.setColumns(20);
        objStatementTextArea.setRows(5);
        jScrollPane3.setViewportView(objStatementTextArea);
        objStatementTextArea.setLineWrap(true);
        objStatementTextArea.setWrapStyleWord(true);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel30.setText("ADDITIONAL INFORMATION");

        jLabel31.setText("Languages:");

        jLabel32.setText("Certificates:");

        jLabel33.setText("Hobbies:");

        languagesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        certificatesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        certificatesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatesTextFieldActionPerformed(evt);
            }
        });

        hobbiesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel34.setText("PERSONAL PHOTO");

        jLabel27.setText("Upload your photo attachment:");

        fileNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fileNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        chooseBtn.setText("Choose");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        genderBtnGrp.add(maleRBtn);
        maleRBtn.setText("Male");
        maleRBtn.setFocusable(false);
        maleRBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        maleRBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        maleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBtnActionPerformed(evt);
            }
        });

        genderBtnGrp.add(femaleRBtn);
        femaleRBtn.setText("Female");
        femaleRBtn.setFocusable(false);
        femaleRBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        femaleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRBtnActionPerformed(evt);
            }
        });

        jLabel35.setText("Gender:");

        jLabel36.setText("Nationality:");

        nationalityBtnGroup.add(ctzRBtn);
        ctzRBtn.setText("Citizen");
        ctzRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctzRBtnActionPerformed(evt);
            }
        });

        nationalityBtnGroup.add(internationalRBtn);
        internationalRBtn.setText("International");
        internationalRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internationalRBtnActionPerformed(evt);
            }
        });

        jLabel37.setText("Status:");

        statusBtnGroup.add(grduatedRBtn);
        grduatedRBtn.setText("graduated");
        grduatedRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grduatedRBtnActionPerformed(evt);
            }
        });

        statusBtnGroup.add(inProcessRBtn);
        inProcessRBtn.setText("In progress");
        inProcessRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inProcessRBtnActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel38.setText("TECHNIQUE SKILLS");

        cplusCBox.setText("C++");
        cplusCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cplusCBoxActionPerformed(evt);
            }
        });

        javaCBox.setText("Java");
        javaCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaCBoxActionPerformed(evt);
            }
        });

        pythonCBox.setText("Python");
        pythonCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonCBoxActionPerformed(evt);
            }
        });

        cCBox.setText("C");
        cCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCBoxActionPerformed(evt);
            }
        });

        phpCBox.setText("PHP");
        phpCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpCBoxActionPerformed(evt);
            }
        });

        jsCBox.setText("Javascript");
        jsCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsCBoxActionPerformed(evt);
            }
        });

        htmlCBox.setText("HTML/CSS");
        htmlCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlCBoxActionPerformed(evt);
            }
        });

        tcpCBox.setText("TCP/IP");
        tcpCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel18)
                            .addComponent(jLabel11)
                            .addComponent(jLabel28)
                            .addComponent(jLabel34)
                            .addComponent(jLabel27)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(269, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(157, 157, 157)
                                .addComponent(createBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj2DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj2DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj2DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj2DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hobbiesTextField)
                                    .addComponent(languagesTextField)
                                    .addComponent(certificatesTextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fileNameTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(71, 71, 71)
                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)
                                .addComponent(countryTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(streetln2TextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetln1TextField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel37))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maleRBtn)
                                            .addComponent(ctzRBtn)
                                            .addComponent(grduatedRBtn))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inProcessRBtn)
                                            .addComponent(femaleRBtn)
                                            .addComponent(internationalRBtn)))
                                    .addComponent(jLabel38)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel14))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(cplusCBox)
                                                        .addGap(42, 42, 42)
                                                        .addComponent(cCBox)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(phpCBox)
                                                .addGap(47, 47, 47)
                                                .addComponent(jsCBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(htmlCBox)
                                                    .addComponent(javaCBox))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pythonCBox)
                                                    .addComponent(tcpCBox))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(createBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maleRBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(femaleRBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ctzRBtn)
                        .addComponent(internationalRBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(grduatedRBtn)
                    .addComponent(inProcessRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cplusCBox)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cCBox)
                        .addComponent(javaCBox)
                        .addComponent(pythonCBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phpCBox)
                    .addComponent(jsCBox)
                    .addComponent(htmlCBox)
                    .addComponent(tcpCBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(pj2DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj2DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj2DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pj2DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(languagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(certificatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(hobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseBtn))
                .addGap(55, 55, 55))
        );

        createScrollPane.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed

        if (validName(fNameTextField.getText())
                &&validName(lNameTextField.getText())
                &&validphone(phoneTextField.getText())
                &&validDate(eduDateFromMTextField.getText(), eduDateFromYTextField.getText(), eduDateToMTextField.getText(), eduDateToYTextField.getText())
                &&validDate(pj1DateFromMTextField.getText(), pj1DateFromYTextField.getText(), pj1DateToMTextField.getText(), pj1DateToYTextField.getText())
                &&validDate(pj2DateFromMTextField.getText(), pj2DateFromYTextField.getText(), pj2DateToMTextField.getText(), pj2DateToYTextField.getText())) 
        {

        Resume resume=resumeHistory.addResume();
        
        resume.setFirstName(fNameTextField.getText());
        resume.setLastName(lNameTextField.getText());
        resume.setPhone(phoneTextField.getText());
        resume.setAffiliation(affiliationTextField.getText());
        resume.setStreetLine1(streetln1TextField.getText());
        resume.setStreetLine2(streetln2TextField.getText());
        resume.setCity(cityTextField.getText());
        resume.setCountry(countryTextField.getText());
        
        //Create Education Info
        resume.setCollegeName(collegeNameTextField.getText());
        String eduFromM = eduDateFromMTextField.getText();
        resume.setEduDateFromM(eduFromM);
        String eduFromY = eduDateFromYTextField.getText();
        resume.setEduDateFromY(eduFromY);
        String eduToM = eduDateToMTextField.getText();
        resume.setEduDateToM(eduToM);
        String eduToY = eduDateToYTextField.getText();
        resume.setEduDateToY(eduToY);
        resume.setSpecialty(specialtyTextField.getText());
        resume.setGpa(gpaTextField.getText());
        
        //Create Projects and Internship Info
        resume.setPNIDateFromM1(pj1DateFromMTextField.getText());//setPNIdateFromM1
        resume.setPNIDateFromY1(pj1DateFromYTextField.getText());
        resume.setPNIDateToM1(pj1DateToMTextField.getText());
        resume.setPNIDateToY1(pj1DateToYTextField.getText());
        resume.setDesctription1(pj1TextArea.getText());
        resume.setPNIDateFromM2(pj2DateFromMTextField.getText());
        resume.setPNIDateFromY2(pj2DateFromYTextField.getText());
        resume.setPNIDateToM2(pj2DateToMTextField.getText());
        resume.setPNIDateToY2(pj2DateToYTextField.getText());
        resume.setDesctription2(pj2TextArea.getText());

        //Create Career Objective Statement
        resume.setDescription(objStatementTextArea.getText());

        //Create additioanl info
        resume.setLanguages(languagesTextField.getText());
        resume.setCertificates(certificatesTextField.getText());
        resume.setHobbies(hobbiesTextField.getText());
        
        
       try {
           resume.setGender(genderBtnGrp.getSelection().getActionCommand());
       }catch (NullPointerException e){
            System.out.println("Unfinished blanks.");
                }
       try{
        resume.setNationality(nationalityBtnGroup.getSelection().getActionCommand());
        }catch (NullPointerException e){
            System.out.println("Unfinished blanks.");
                }
       try{
        resume.setStatus(statusBtnGroup.getSelection().getActionCommand());
        }catch (NullPointerException e){
            System.out.println("Unfinished blanks.");
                }
        
        //Create Tech Skilss
        try{
        String skill ="";
            if (!(cCBox.isSelected()
                    ||cplusCBox.isSelected()
                    ||javaCBox.isSelected()
                    ||pythonCBox.isSelected()
                    ||phpCBox.isSelected()
                    ||jsCBox.isSelected()
                    ||htmlCBox.isSelected()
                    ||tcpCBox.isSelected())){
                skill = "No tech skills.";
            }
            if (cCBox.isSelected()) {
                skill = cCBox.getActionCommand();
            } 
            if (cplusCBox.isSelected()) {
                skill += "  " +cplusCBox.getActionCommand();
            }
            if (javaCBox.isSelected()) {
                skill += "  " + javaCBox.getActionCommand();
            } 
            if (pythonCBox.isSelected()) {
                skill += "  " +pythonCBox.getActionCommand();
            }
            if (phpCBox.isSelected()) {
                skill += "  " +phpCBox.getActionCommand();
            } 
            if (jsCBox.isSelected()) {
                skill += "  " +jsCBox.getActionCommand();
            }
            if (htmlCBox.isSelected()) {
                skill += "  " +htmlCBox.getActionCommand();
            } 
            if (tcpCBox.isSelected()) {
                skill += "  " +tcpCBox.getActionCommand();
            }
        resume.setTechSkills(skill);
        }catch (NullPointerException e){
            System.out.println("Unfinished blanks.");
                }
        
        //Create photo
        try{
            pht1.setImage(pht1.getImage().getScaledInstance(121, 121, Image.SCALE_DEFAULT));
            resume.setPhoto(pht1);
        }catch (NullPointerException e){
            System.out.println("Unfinished blanks.");
                }
        
        JOptionPane.showMessageDialog(null, "Product created successfully.");
        
        //Clear all field for UX
        //Basic info
        fNameTextField.setText("");
        lNameTextField.setText("");
        phoneTextField.setText("");
        affiliationTextField.setText("");
        streetln1TextField.setText("");
        streetln2TextField.setText("");
        cityTextField.setText("");
        countryTextField.setText("");

        //Education Info
        collegeNameTextField.setText("");
        eduDateFromMTextField.setText("");
        eduDateFromYTextField.setText("");
        eduDateToMTextField.setText("");
        eduDateToYTextField.setText("");
        specialtyTextField.setText("");
        gpaTextField.setText("");

        //Projects and Internship Info
        pj1DateFromMTextField.setText("");//setPNIdateFromM1
        pj1DateFromYTextField.setText("");
        pj1DateToMTextField.setText("");
        pj1DateToYTextField.setText("");
        pj1TextArea.setText("");
        pj2DateFromMTextField.setText("");
        pj2DateFromYTextField.setText("");
        pj2DateToMTextField.setText("");
        pj2DateToYTextField.setText("");
        pj2TextArea.setText("");
        
        //Career Objective Statement
        objStatementTextArea.setText("");
        //additioanl info
        
        languagesTextField.setText("");
        certificatesTextField.setText("");
        hobbiesTextField.setText("");
        }
        
        

    }//GEN-LAST:event_createBtnActionPerformed
    private String cad;
    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBtnActionPerformed

        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG PNG GIF Images","jpg","gif","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(CreatePanel.this);
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            cad = chooser.getCurrentDirectory() + "/" + chooser.getSelectedFile().getName();
            fileNameTextField.setText(cad);
            pht1 = new ImageIcon(cad);
            
        }
    }//GEN-LAST:event_chooseBtnActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    private void certificatesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificatesTextFieldActionPerformed

    private void pj2DateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj2DateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj2DateFromYTextFieldActionPerformed

    private void pj1DateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj1DateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj1DateFromYTextFieldActionPerformed

    private void eduDateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromYTextFieldActionPerformed

    private void eduDateFromMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromMTextFieldActionPerformed

    private void maleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBtnActionPerformed
        maleRBtn.setActionCommand("Male");
    }//GEN-LAST:event_maleRBtnActionPerformed

    private void femaleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRBtnActionPerformed
        femaleRBtn.setActionCommand("Female");
    }//GEN-LAST:event_femaleRBtnActionPerformed

    private void ctzRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctzRBtnActionPerformed
        ctzRBtn.setActionCommand("Local citizen");
    }//GEN-LAST:event_ctzRBtnActionPerformed

    private void grduatedRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grduatedRBtnActionPerformed
        grduatedRBtn.setActionCommand("Graduated");
    }//GEN-LAST:event_grduatedRBtnActionPerformed

    private void internationalRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internationalRBtnActionPerformed
        internationalRBtn.setActionCommand("International");
        
    }//GEN-LAST:event_internationalRBtnActionPerformed

    private void inProcessRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inProcessRBtnActionPerformed
        inProcessRBtn.setActionCommand("In Process");
    }//GEN-LAST:event_inProcessRBtnActionPerformed

    private void cCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCBoxActionPerformed
        cCBox.setActionCommand("C");
    }//GEN-LAST:event_cCBoxActionPerformed

    private void cplusCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cplusCBoxActionPerformed
        cplusCBox.setActionCommand("C++");
    }//GEN-LAST:event_cplusCBoxActionPerformed

    private void javaCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaCBoxActionPerformed
        javaCBox.setActionCommand("Java");
    }//GEN-LAST:event_javaCBoxActionPerformed

    private void pythonCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonCBoxActionPerformed
        pythonCBox.setActionCommand("Python");
    }//GEN-LAST:event_pythonCBoxActionPerformed

    private void phpCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpCBoxActionPerformed
        phpCBox.setActionCommand("PHP");
        
    }//GEN-LAST:event_phpCBoxActionPerformed

    private void jsCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsCBoxActionPerformed
        jsCBox.setActionCommand("Javascript");
    }//GEN-LAST:event_jsCBoxActionPerformed

    private void htmlCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlCBoxActionPerformed
        htmlCBox.setActionCommand("HTML/CSS");
    }//GEN-LAST:event_htmlCBoxActionPerformed

    private void tcpCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpCBoxActionPerformed
        tcpCBox.setActionCommand("TCP/TP");
    }//GEN-LAST:event_tcpCBoxActionPerformed

    private void eduDateToMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateToMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateToMTextFieldActionPerformed

    private void pj2DateToMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj2DateToMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj2DateToMTextFieldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JCheckBox cCBox;
    private javax.swing.JTextField certificatesTextField;
    private javax.swing.JButton chooseBtn;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField collegeNameTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JCheckBox cplusCBox;
    private javax.swing.JButton createBtn;
    private javax.swing.JScrollPane createScrollPane;
    private javax.swing.JRadioButton ctzRBtn;
    private javax.swing.JTextField eduDateFromMTextField;
    private javax.swing.JTextField eduDateFromYTextField;
    private javax.swing.JTextField eduDateToMTextField;
    private javax.swing.JTextField eduDateToYTextField;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JRadioButton femaleRBtn;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.ButtonGroup genderBtnGrp;
    private javax.swing.JTextField gpaTextField;
    private javax.swing.JRadioButton grduatedRBtn;
    private javax.swing.JTextField hobbiesTextField;
    private javax.swing.JCheckBox htmlCBox;
    private javax.swing.JRadioButton inProcessRBtn;
    private javax.swing.JRadioButton internationalRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox javaCBox;
    private javax.swing.JCheckBox jsCBox;
    private javax.swing.JTextField lNameTextField;
    private javax.swing.JTextField languagesTextField;
    private javax.swing.JRadioButton maleRBtn;
    private javax.swing.ButtonGroup nationalityBtnGroup;
    private javax.swing.JTextArea objStatementTextArea;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JCheckBox phpCBox;
    private javax.swing.JTextField pj1DateFromMTextField;
    private javax.swing.JTextField pj1DateFromYTextField;
    private javax.swing.JTextField pj1DateToMTextField;
    private javax.swing.JTextField pj1DateToYTextField;
    private javax.swing.JTextArea pj1TextArea;
    private javax.swing.JTextField pj2DateFromMTextField;
    private javax.swing.JTextField pj2DateFromYTextField;
    private javax.swing.JTextField pj2DateToMTextField;
    private javax.swing.JTextField pj2DateToYTextField;
    private javax.swing.JTextArea pj2TextArea;
    private javax.swing.JCheckBox pythonCBox;
    private javax.swing.JTextField specialtyTextField;
    private javax.swing.ButtonGroup statusBtnGroup;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JTextField streetln2TextField;
    private javax.swing.JCheckBox tcpCBox;
    // End of variables declaration//GEN-END:variables
}
