/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Resume.BasicInfo;
import Resume.Education;
import Resume.ProjectsandInternship;
import Resume.CareerObjStatement;
import Resume.AdditionalInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author leslie
 */
public class CreatePanel extends javax.swing.JPanel {
    
    JFileChooser chooser = new JFileChooser();
    
    private BasicInfo basicInfo;
    private Education education;
    private ProjectsandInternship projectsandInternship1;
    private ProjectsandInternship projectsandInternship2;
    private CareerObjStatement careerObjStatement;
    private AdditionalInfo additionalInfo;
    public CreatePanel(BasicInfo basicInfo, Education education, ProjectsandInternship projectsandInternship1,ProjectsandInternship projectsandInternship2, CareerObjStatement careerObjStatement, AdditionalInfo additionalInfo) {
        initComponents();
        this.basicInfo = basicInfo;
        this.education = education;
        this.projectsandInternship1 = projectsandInternship1;
        this.projectsandInternship2 = projectsandInternship2;
        this.careerObjStatement = careerObjStatement;
        this.additionalInfo = additionalInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        lNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        streetln1TextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        collegeNameTextField = new javax.swing.JTextField();
        specialtyTextField = new javax.swing.JTextField();
        gpaTextField = new javax.swing.JTextField();
        eduDateFromMTextField = new javax.swing.JTextField();
        eduDateToMTextField = new javax.swing.JTextField();
        eduDateFromYTextField = new javax.swing.JTextField();
        eduDateToYTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pj1DateFromMTextField = new javax.swing.JTextField();
        pj1DateToMTextField = new javax.swing.JTextField();
        pj1DateFromYTextField = new javax.swing.JTextField();
        pj1DateToYTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pj1TextArea = new javax.swing.JTextArea();
        pj2DateFromMTextField = new javax.swing.JTextField();
        pj2DateToMTextField = new javax.swing.JTextField();
        pj2DateFromYTextField = new javax.swing.JTextField();
        pj2DateToYTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pj2TextArea = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objStatementTextArea = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        languagesTextField = new javax.swing.JTextField();
        certificatesTextField = new javax.swing.JTextField();
        hobbiesTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        chooseBtn = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        createBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 248, 248));

        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel1.setText("Create a Resume");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("BASIC INFORMATION");

        jLabel5.setText("Street Line 1:");

        fNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Street Line 2:");

        jLabel7.setText("City:");

        jLabel8.setText("Country:");

        jLabel9.setText("E-mail:");

        jLabel10.setText("Affiliation:");

        emailTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        affiliationTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        streetln1TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        streetln2TextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cityTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        countryTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("EDUCATION ");

        jLabel12.setText("Date:");

        jLabel13.setText("From");

        jLabel14.setText("To");

        jLabel15.setText("College Name:");

        jLabel16.setText("Specialty:");

        jLabel17.setText("GPA:");

        collegeNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        specialtyTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gpaTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        eduDateFromMTextField.setText("mm");
        eduDateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateFromMTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromMTextFieldActionPerformed(evt);
            }
        });

        eduDateToMTextField.setText("mm");
        eduDateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateToMTextField.setFocusTraversalKeysEnabled(false);

        eduDateFromYTextField.setText("yyyy");
        eduDateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateFromYTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromYTextFieldActionPerformed(evt);
            }
        });

        eduDateToYTextField.setText("yyyy");
        eduDateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eduDateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("PROJECTS AND INTERNSHIPS");

        pj1DateFromMTextField.setText("mm");
        pj1DateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateFromMTextField.setFocusTraversalKeysEnabled(false);

        pj1DateToMTextField.setText("mm");
        pj1DateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateToMTextField.setFocusTraversalKeysEnabled(false);

        pj1DateFromYTextField.setText("yyyy");
        pj1DateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateFromYTextField.setFocusTraversalKeysEnabled(false);
        pj1DateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj1DateFromYTextFieldActionPerformed(evt);
            }
        });

        pj1DateToYTextField.setText("yyyy");
        pj1DateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj1DateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel19.setText("Date:");

        jLabel20.setText("From");

        jLabel21.setText("To");

        jLabel22.setText("Description:");

        pj1TextArea.setColumns(20);
        pj1TextArea.setRows(5);
        jScrollPane1.setViewportView(pj1TextArea);

        pj2DateFromMTextField.setText("mm");
        pj2DateFromMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pj2DateToMTextField.setText("mm");
        pj2DateToMTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pj2DateFromYTextField.setText("yyyy");
        pj2DateFromYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pj2DateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj2DateFromYTextFieldActionPerformed(evt);
            }
        });

        pj2DateToYTextField.setText("yyyy");
        pj2DateToYTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setText("Date:");

        jLabel24.setText("From");

        jLabel25.setText("To");

        jLabel26.setText("Description:");

        pj2TextArea.setColumns(20);
        pj2TextArea.setRows(5);
        jScrollPane2.setViewportView(pj2TextArea);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("CAREER OBJECTIVE STATEMENT");

        jLabel29.setText("Description:");

        objStatementTextArea.setColumns(20);
        objStatementTextArea.setRows(5);
        jScrollPane3.setViewportView(objStatementTextArea);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel30.setText("ADDITIONAL INFORMATION");

        jLabel31.setText("Languages:");

        jLabel32.setText("Certificates:");

        jLabel33.setText("Hobbies:");

        languagesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        certificatesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        certificatesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatesTextFieldActionPerformed(evt);
            }
        });

        hobbiesTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel34.setText("PERSONAL PHOTO");

        jLabel27.setText("Upload your photo attachment:");

        fileNameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fileNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        chooseBtn.setText("Choose");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fileNameTextField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chooseBtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(streetln2TextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(streetln1TextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel29)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel26))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj2DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj2DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj2DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj2DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jScrollPane2))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(66, 66, 66)
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel9))
                                                    .addGap(28, 28, 28)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel3)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                    .addGap(46, 46, 46)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                                        .addComponent(countryTextField)))
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel17))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(0, 5, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel22))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jLabel20)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jScrollPane1)))))
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel33))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hobbiesTextField)
                                        .addComponent(languagesTextField)
                                        .addComponent(certificatesTextField)))))))
                .addGap(38, 38, 38)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(createBtn))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(pj2DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj2DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj2DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj2DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(languagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(certificatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(hobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseBtn))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eduDateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromYTextFieldActionPerformed

    private void pj1DateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj1DateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj1DateFromYTextFieldActionPerformed

    private void pj2DateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj2DateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj2DateFromYTextFieldActionPerformed

    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBtnActionPerformed
        
        String cad;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG PNG GIF Images","jpg","gif","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(CreatePanel.this);
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            cad = chooser.getCurrentDirectory() + "/" + chooser.getSelectedFile().getName();
            fileNameTextField.setText(cad);
        }
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_chooseBtnActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    private void certificatesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificatesTextFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        
        //Create Basic Info
        basicInfo.setFirstName(fNameTextField.getText());
        basicInfo.setLastName(lNameTextField.getText());
        basicInfo.setEmail(emailTextField.getText());
        basicInfo.setAffiliation(affiliationTextField.getText());
        basicInfo.setStreetLine1(streetln1TextField.getText());
        basicInfo.setStreetLine2(streetln2TextField.getText());
        basicInfo.setCity(cityTextField.getText());
        basicInfo.setCountry(countryTextField.getText());
        
        //Create Education Info
        education.setCollegeName(collegeNameTextField.getText());
        education.setDateFromM(eduDateFromMTextField.getText());
        education.setDateFromY(eduDateFromYTextField.getText());
        education.setDateToM(eduDateToMTextField.getText());
        education.setDateToY(eduDateToYTextField.getText());
        education.setSpecialty(specialtyTextField.getText());
        education.setGpa(gpaTextField.getText());
        
        //Create Projects and Internship Info
        projectsandInternship1.setDateFromM(pj1DateFromMTextField.getText());
        projectsandInternship1.setDateFromY(pj1DateFromMTextField.getText());
        projectsandInternship1.setDateToM(pj1DateToMTextField.getText());
        projectsandInternship1.setDateToY(pj1DateToYTextField.getText());
        projectsandInternship1.setDesctription(pj1TextArea.getText());
        projectsandInternship2.setDateFromM(pj2DateFromMTextField.getText());
        projectsandInternship2.setDateFromY(pj2DateFromMTextField.getText());
        projectsandInternship2.setDateToM(pj2DateToMTextField.getText());
        projectsandInternship2.setDateToY(pj2DateToYTextField.getText());
        projectsandInternship2.setDesctription(pj2TextArea.getText());
        
        //Create Career Objective Statement
        careerObjStatement.setDescription(objStatementTextArea.getText());
        
        //Create additioanl info
        additionalInfo.setLanguages(languagesTextField.getText());
        additionalInfo.setCertificates(certificatesTextField.getText());
        additionalInfo.setHobbies(hobbiesTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Product created successfully.");
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void eduDateFromMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromMTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JTextField certificatesTextField;
    private javax.swing.JButton chooseBtn;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField collegeNameTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField eduDateFromMTextField;
    private javax.swing.JTextField eduDateFromYTextField;
    private javax.swing.JTextField eduDateToMTextField;
    private javax.swing.JTextField eduDateToYTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JTextField gpaTextField;
    private javax.swing.JTextField hobbiesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lNameTextField;
    private javax.swing.JTextField languagesTextField;
    private javax.swing.JTextArea objStatementTextArea;
    private javax.swing.JTextField pj1DateFromMTextField;
    private javax.swing.JTextField pj1DateFromYTextField;
    private javax.swing.JTextField pj1DateToMTextField;
    private javax.swing.JTextField pj1DateToYTextField;
    private javax.swing.JTextArea pj1TextArea;
    private javax.swing.JTextField pj2DateFromMTextField;
    private javax.swing.JTextField pj2DateFromYTextField;
    private javax.swing.JTextField pj2DateToMTextField;
    private javax.swing.JTextField pj2DateToYTextField;
    private javax.swing.JTextArea pj2TextArea;
    private javax.swing.JTextField specialtyTextField;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JTextField streetln2TextField;
    // End of variables declaration//GEN-END:variables
}
