/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Resume.BasicInfo;
import Resume.Education;
import Resume.ProjectsandInternship;
import Resume.CareerObjStatement;
import Resume.AdditionalInfo;
/**
 *
 * @author leslie
 */
public class DisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form DispalyPanel
     */
    public DisplayPanel(BasicInfo basicInfo, Education education, ProjectsandInternship projectsandInternship1,ProjectsandInternship projectsandInternship2, CareerObjStatement careerObjStatement, AdditionalInfo additionalInfo) {
        initComponents();
        display(basicInfo,  education,  projectsandInternship1, projectsandInternship2,  careerObjStatement, additionalInfo);
        
    }
    
    private Void display(BasicInfo basicInfo, Education education, ProjectsandInternship projectsandInternship1,ProjectsandInternship projectsandInternship2, CareerObjStatement careerObjStatement, AdditionalInfo additionalInfo) {
        
        String basicfName = basicInfo.getFirstName();
        fNameTextField.setText(basicfName);
        String basiclName = basicInfo.getLastName();
        lNameTextField.setText(basiclName);
        String bEmail = basicInfo.getEmail();
        emailTextField.setText(bEmail);
        String bAffiliation = basicInfo.getAffiliation();
        affiliationTextField.setText(bAffiliation);
        String bLn1 = basicInfo.getStreetLine1();
        streetln1TextField.setText(bLn1);
        String bLn2 = basicInfo.getStreetLine2();
        streetln2TextField.setText(bLn2);
        String bcity = basicInfo.getCity();
        cityTextField.setText(bcity);
        String bcountry = basicInfo.getCountry();
        countryTextField.setText(bcountry);
        
        
        //display photo
        photoTagField.setIcon(basicInfo.getPhoto());
        
        String ename = education.getCollegeName();
        collegeNameTextField.setText(ename);
        String especty = education.getSpecialty();
        specialtyTextField.setText(especty);
        String edfm = education.getDateFromM();
        eduDateFromMTextField.setText(edfm);
        String edfy = education.getDateFromY();
        eduDateFromYTextField.setText(edfy);
        String edtm = education.getDateToM();
        eduDateToMTextField.setText(edtm);
        String edty = education.getDateToY();
        eduDateToYTextField.setText(edty);
        
        String gpa = education.getGpa();
        gpaTextField.setText(gpa);
        
        String p1dfm = projectsandInternship1.getDateFromM();
        pj1DateFromMTextField.setText(p1dfm);
        String p1dfy = projectsandInternship1.getDateFromY();
        pj1DateFromYTextField.setText(p1dfy);
        String p1dtm = projectsandInternship1.getDateToM();
        pj1DateToMTextField.setText(p1dtm);
        String p1dty = projectsandInternship1.getDateToY();
        pj1DateToYTextField.setText(p1dty);
        
        String p2dfm = projectsandInternship2.getDateFromM();
        pj2DateFromMTextField1.setText(p2dfm);
        String p2dfy = projectsandInternship2.getDateFromY();
        pj2DateFromYTextField1.setText(p2dfy);
        String p2dtm = projectsandInternship2.getDateToM();
        pj2DateToMTextField1.setText(p2dtm);
        String p2dty = projectsandInternship2.getDateToY();
        pj2DateToYTextField1.setText(p2dty);
        
        String p1des = projectsandInternship1.getDesctription();
        pj1TextArea.setText(p1des);
        
        String p2des = projectsandInternship2.getDesctription();
        pj2TextArea.setText(p2des);
        
        
        
        String career = careerObjStatement.getDescription();
        objStatementTextArea.setText(career);
        
        
        String addlangg = additionalInfo.getLanguages();
        languagesTextField.setText(addlangg);
        String addcert = additionalInfo.getCertificates();
        certificatesTextField.setText(addcert);
        String hbs = additionalInfo.getHobbies();
        hobbiesTextField.setText(hbs);
        
        
        
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        pj1DateFromMTextField = new javax.swing.JTextField();
        pj1DateToMTextField = new javax.swing.JTextField();
        pj1DateFromYTextField = new javax.swing.JTextField();
        pj1DateToYTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pj1TextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        collegeNameTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pj2TextArea = new javax.swing.JTextArea();
        specialtyTextField = new javax.swing.JTextField();
        gpaTextField = new javax.swing.JTextField();
        eduDateFromMTextField = new javax.swing.JTextField();
        eduDateToMTextField = new javax.swing.JTextField();
        eduDateFromYTextField = new javax.swing.JTextField();
        eduDateToYTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objStatementTextArea = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        languagesTextField = new javax.swing.JTextField();
        certificatesTextField = new javax.swing.JTextField();
        hobbiesTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        pj2DateFromMTextField1 = new javax.swing.JTextField();
        pj2DateToMTextField1 = new javax.swing.JTextField();
        pj2DateFromYTextField1 = new javax.swing.JTextField();
        pj2DateToYTextField1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JLabel();
        lNameTextField = new javax.swing.JLabel();
        streetln1TextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        photoTagField = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 247, 237));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("PROJECTS AND INTERNSHIPS");

        pj1DateFromMTextField.setBackground(new java.awt.Color(240, 247, 237));
        pj1DateFromMTextField.setText("mm");
        pj1DateFromMTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj1DateFromMTextField.setFocusTraversalKeysEnabled(false);
        pj1DateFromMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj1DateFromMTextFieldActionPerformed(evt);
            }
        });

        pj1DateToMTextField.setBackground(new java.awt.Color(240, 247, 237));
        pj1DateToMTextField.setText("mm");
        pj1DateToMTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj1DateToMTextField.setFocusTraversalKeysEnabled(false);
        pj1DateToMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj1DateToMTextFieldActionPerformed(evt);
            }
        });

        pj1DateFromYTextField.setBackground(new java.awt.Color(240, 247, 237));
        pj1DateFromYTextField.setText("yyyy");
        pj1DateFromYTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj1DateFromYTextField.setFocusTraversalKeysEnabled(false);
        pj1DateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj1DateFromYTextFieldActionPerformed(evt);
            }
        });

        pj1DateToYTextField.setBackground(new java.awt.Color(240, 247, 237));
        pj1DateToYTextField.setText("yyyy");
        pj1DateToYTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj1DateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel20.setText("/");

        jLabel21.setText("~");

        pj1TextArea.setColumns(20);
        pj1TextArea.setRows(5);
        jScrollPane1.setViewportView(pj1TextArea);
        pj1TextArea.setLineWrap(true);
        pj1TextArea.setWrapStyleWord(true);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("EDUCATION ");

        jLabel14.setText("~");

        collegeNameTextField.setBackground(new java.awt.Color(240, 247, 237));
        collegeNameTextField.setText("College Name");
        collegeNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pj2TextArea.setColumns(20);
        pj2TextArea.setRows(5);
        jScrollPane2.setViewportView(pj2TextArea);
        pj1TextArea.setLineWrap(true);
        pj1TextArea.setWrapStyleWord(true);

        specialtyTextField.setBackground(new java.awt.Color(240, 247, 237));
        specialtyTextField.setText("Specialty");
        specialtyTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        specialtyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialtyTextFieldActionPerformed(evt);
            }
        });

        gpaTextField.setBackground(new java.awt.Color(240, 247, 237));
        gpaTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        eduDateFromMTextField.setBackground(new java.awt.Color(240, 247, 237));
        eduDateFromMTextField.setText("mm");
        eduDateFromMTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eduDateFromMTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromMTextFieldActionPerformed(evt);
            }
        });

        eduDateToMTextField.setBackground(new java.awt.Color(240, 247, 237));
        eduDateToMTextField.setText("mm");
        eduDateToMTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eduDateToMTextField.setFocusTraversalKeysEnabled(false);
        eduDateToMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateToMTextFieldActionPerformed(evt);
            }
        });

        eduDateFromYTextField.setBackground(new java.awt.Color(240, 247, 237));
        eduDateFromYTextField.setText("yyyy");
        eduDateFromYTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eduDateFromYTextField.setFocusTraversalKeysEnabled(false);
        eduDateFromYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduDateFromYTextFieldActionPerformed(evt);
            }
        });

        eduDateToYTextField.setBackground(new java.awt.Color(240, 247, 237));
        eduDateToYTextField.setText("yyyy");
        eduDateToYTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eduDateToYTextField.setFocusTraversalKeysEnabled(false);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("CAREER OBJECTIVE STATEMENT");

        objStatementTextArea.setColumns(20);
        objStatementTextArea.setRows(5);
        jScrollPane3.setViewportView(objStatementTextArea);
        pj1TextArea.setLineWrap(true);
        pj1TextArea.setWrapStyleWord(true);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel30.setText("ADDITIONAL INFORMATION");

        languagesTextField.setBackground(new java.awt.Color(240, 247, 237));
        languagesTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        certificatesTextField.setBackground(new java.awt.Color(240, 247, 237));
        certificatesTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        certificatesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatesTextFieldActionPerformed(evt);
            }
        });

        hobbiesTextField.setBackground(new java.awt.Color(240, 247, 237));
        hobbiesTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel33.setText("Hobbies:");

        jLabel32.setText("Certificates:");

        jLabel31.setText("Languages:");

        jLabel1.setText("/");

        jLabel2.setText("/");

        jLabel3.setText("GPA");

        jLabel34.setText("/");

        pj2DateFromMTextField1.setBackground(new java.awt.Color(240, 247, 237));
        pj2DateFromMTextField1.setText("mm");
        pj2DateFromMTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj2DateFromMTextField1.setFocusTraversalKeysEnabled(false);

        pj2DateToMTextField1.setBackground(new java.awt.Color(240, 247, 237));
        pj2DateToMTextField1.setText("mm");
        pj2DateToMTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj2DateToMTextField1.setFocusTraversalKeysEnabled(false);

        pj2DateFromYTextField1.setBackground(new java.awt.Color(240, 247, 237));
        pj2DateFromYTextField1.setText("yyyy");
        pj2DateFromYTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj2DateFromYTextField1.setFocusTraversalKeysEnabled(false);
        pj2DateFromYTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pj2DateFromYTextField1ActionPerformed(evt);
            }
        });

        pj2DateToYTextField1.setBackground(new java.awt.Color(240, 247, 237));
        pj2DateToYTextField1.setText("yyyy");
        pj2DateToYTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pj2DateToYTextField1.setFocusTraversalKeysEnabled(false);

        jLabel35.setText("/");

        jLabel36.setText("/");

        jLabel37.setText("~");

        fNameTextField.setFont(new java.awt.Font("Savoye LET", 1, 36)); // NOI18N
        fNameTextField.setText("fname");

        lNameTextField.setFont(new java.awt.Font("Savoye LET", 1, 36)); // NOI18N
        lNameTextField.setText("lname");

        streetln1TextField.setBackground(new java.awt.Color(240, 247, 237));
        streetln1TextField.setText("Street Line 1");
        streetln1TextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        streetln1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetln1TextFieldActionPerformed(evt);
            }
        });

        streetln2TextField.setBackground(new java.awt.Color(240, 247, 237));
        streetln2TextField.setText("Street Line 2");
        streetln2TextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cityTextField.setBackground(new java.awt.Color(240, 247, 237));
        cityTextField.setText("City");
        cityTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        countryTextField.setBackground(new java.awt.Color(240, 247, 237));
        countryTextField.setText("Country");
        countryTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        emailTextField.setBackground(new java.awt.Color(240, 247, 237));
        emailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        affiliationTextField.setBackground(new java.awt.Color(240, 247, 237));
        affiliationTextField.setText("Affiliation");
        affiliationTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        photoTagField.setText("photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(fNameTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNameTextField)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(38, 38, 38)
                                .addComponent(hobbiesTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(certificatesTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(23, 23, 23)
                                .addComponent(languagesTextField))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel20)
                                .addGap(0, 0, 0)
                                .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel34)
                                .addGap(0, 0, 0)
                                .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(photoTagField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pj2DateFromMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel35)
                                .addGap(0, 0, 0)
                                .addComponent(pj2DateFromYTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pj2DateToMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel36)
                                .addGap(0, 0, 0)
                                .addComponent(pj2DateToYTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel14)
                                .addGap(0, 0, 0)
                                .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(0, 0, 0)
                                .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameTextField)
                    .addComponent(lNameTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoTagField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(eduDateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eduDateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(collegeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(gpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(pj1DateFromMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj1DateToMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj1DateFromYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj1DateToYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel37)
                        .addComponent(pj2DateFromMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj2DateToMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj2DateFromYTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pj2DateToYTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(languagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(certificatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(hobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pj1DateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj1DateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj1DateFromYTextFieldActionPerformed

    private void eduDateFromYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromYTextFieldActionPerformed

    private void certificatesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificatesTextFieldActionPerformed

    private void eduDateToMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateToMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateToMTextFieldActionPerformed

    private void pj2DateFromYTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj2DateFromYTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj2DateFromYTextField1ActionPerformed

    private void pj1DateFromMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj1DateFromMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj1DateFromMTextFieldActionPerformed

    private void pj1DateToMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pj1DateToMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pj1DateToMTextFieldActionPerformed

    private void streetln1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetln1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetln1TextFieldActionPerformed

    private void eduDateFromMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduDateFromMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduDateFromMTextFieldActionPerformed

    private void specialtyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialtyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialtyTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JTextField certificatesTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField collegeNameTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField eduDateFromMTextField;
    private javax.swing.JTextField eduDateFromYTextField;
    private javax.swing.JTextField eduDateToMTextField;
    private javax.swing.JTextField eduDateToYTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel fNameTextField;
    private javax.swing.JTextField gpaTextField;
    private javax.swing.JTextField hobbiesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lNameTextField;
    private javax.swing.JTextField languagesTextField;
    private javax.swing.JTextArea objStatementTextArea;
    private javax.swing.JLabel photoTagField;
    private javax.swing.JTextField pj1DateFromMTextField;
    private javax.swing.JTextField pj1DateFromYTextField;
    private javax.swing.JTextField pj1DateToMTextField;
    private javax.swing.JTextField pj1DateToYTextField;
    private javax.swing.JTextArea pj1TextArea;
    private javax.swing.JTextField pj2DateFromMTextField1;
    private javax.swing.JTextField pj2DateFromYTextField1;
    private javax.swing.JTextField pj2DateToMTextField1;
    private javax.swing.JTextField pj2DateToYTextField1;
    private javax.swing.JTextArea pj2TextArea;
    private javax.swing.JTextField specialtyTextField;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JTextField streetln2TextField;
    // End of variables declaration//GEN-END:variables
}
