/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supplier supplier;
    
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, Supplier supplier) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = supplier;
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mngProductCatalogBtn = new javax.swing.JButton();
        reviewProductPerformBtn = new javax.swing.JButton();
        updatePersonalProfileBtn = new javax.swing.JButton();
        mngStaffBtn = new javax.swing.JButton();

        jLabel1.setText("My Work Area (Product Manager Role)");

        mngProductCatalogBtn.setText("Manage Product Catalog >>");
        mngProductCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngProductCatalogBtnActionPerformed(evt);
            }
        });

        reviewProductPerformBtn.setText("Review Product Performance>>");
        reviewProductPerformBtn.setEnabled(false);

        updatePersonalProfileBtn.setText("Update Personal Profile >>");
        updatePersonalProfileBtn.setEnabled(false);

        mngStaffBtn.setText("Manage Staff >>");
        mngStaffBtn.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reviewProductPerformBtn)
                            .addComponent(mngProductCatalogBtn)
                            .addComponent(updatePersonalProfileBtn)
                            .addComponent(mngStaffBtn))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(mngProductCatalogBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewProductPerformBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePersonalProfileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mngStaffBtn)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngProductCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngProductCatalogBtnActionPerformed
        ManageProductCatalogJPanel manageSupplierCatalogJPanel = new ManageProductCatalogJPanel(userProcessContainer, supplier);
        userProcessContainer.add("manageSupplierCatalogJPanel", manageSupplierCatalogJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngProductCatalogBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngProductCatalogBtn;
    private javax.swing.JButton mngStaffBtn;
    private javax.swing.JButton reviewProductPerformBtn;
    private javax.swing.JButton updatePersonalProfileBtn;
    // End of variables declaration//GEN-END:variables
}
