/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.vendorRole;

import Business.Product;
import Business.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    private ProductDirectory productDirectory;
    private JPanel userProcessContainerJPanel;
    private String vendorName;
    
    public CreateProductJPanel(ProductDirectory productDirectory, JPanel userProcessContainerJPanel, String vendorName) {
        initComponents();
        this.productDirectory = productDirectory;
        this.userProcessContainerJPanel = userProcessContainerJPanel;
        this.vendorName = vendorName;
    }
    
//    public boolean validPrice(String str){
//        boolean isNum = false;
//        boolean digit;
//        for(int i = str.length();--i>=0;){
//            if (!Character.isDigit(str.charAt(i))){
//                char thisdigit = str[i-1];
//                if (str.equals(ABORT)) {
//                    
//                }
//                isNum = false;
//            break;
//            }
//        isNum = true;
//        }
//        if (isNum && str.length()==10) {
//            return true;
//        } else {
//            JOptionPane.showMessageDialog(null, "Please fill a valid USA phone number");
//            return false;
//        }
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modelNumTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        featureTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        basicPriceTextField = new javax.swing.JTextField();
        ceilingPriceTextField = new javax.swing.JTextField();
        floorPriceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 36)); // NOI18N
        jLabel2.setText("Create a New Product");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel1.setText("Product Name:");

        productNameTextField.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        productNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel3.setText("Model Number:");

        modelNumTextField.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N

        featureTextArea.setColumns(20);
        featureTextArea.setRows(3);
        jScrollPane2.setViewportView(featureTextArea);

        jLabel4.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel4.setText("Description:");

        jLabel5.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel5.setText("Base Price:");

        jLabel6.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel6.setText("Ceiling Price:");

        jLabel7.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel7.setText("Floor Price:");

        jLabel8.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel8.setText("Features:");

        basicPriceTextField.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N

        ceilingPriceTextField.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N

        floorPriceTextField.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 13)); // NOI18N
        jLabel9.setText("Catagory:");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "Printer", "Hardware", "Software" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        descriptionTextArea1.setColumns(20);
        descriptionTextArea1.setRows(3);
        jScrollPane3.setViewportView(descriptionTextArea1);

        jLabel10.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 2, 12)); // NOI18N
        jLabel10.setText("Please fill features with short statement seperated by \":\"");
        jLabel10.setToolTipText("");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(modelNumTextField)
                            .addComponent(basicPriceTextField)
                            .addComponent(ceilingPriceTextField)
                            .addComponent(floorPriceTextField)
                            .addComponent(productNameTextField)
                            .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(basicPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ceilingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(floorPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(createBtn))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainerJPanel.remove(this);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.previous(userProcessContainerJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        
        Product product = productDirectory.addProduct();
        
        product.setVendor(vendorName);
        product.setUnderCatalog(categoryComboBox.getSelectedItem().toString());
        product.setName(productNameTextField.getText());
        product.setModelNum(modelNumTextField.getText());
        product.setBasePrice(Float.parseFloat(basicPriceTextField.getText()));
        product.setCeilingPrice(Float.parseFloat(ceilingPriceTextField.getText()));
        product.setFloorPrice(Float.parseFloat(floorPriceTextField.getText()));
        product.setDescription(descriptionTextArea1.getText());
        product.setFeatures(featureTextArea.getText());
        
        JOptionPane.showMessageDialog(null, "Product created successfully.");
        
        productNameTextField.setText("");
        modelNumTextField.setText("");
        basicPriceTextField.setText("");
        ceilingPriceTextField.setText("");
        floorPriceTextField.setText("");
        descriptionTextArea1.setText("");
        featureTextArea.setText("");
      
    }//GEN-LAST:event_createBtnActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField basicPriceTextField;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextField ceilingPriceTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextArea descriptionTextArea1;
    private javax.swing.JTextArea featureTextArea;
    private javax.swing.JTextField floorPriceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField productNameTextField;
    // End of variables declaration//GEN-END:variables
}
