/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSigns;
import Business.VitalSignsHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author leslie
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
    
    private VitalSignsHistory vsh;
    public CreateVitalJPanel(VitalSignsHistory vsh) {
        initComponents();
        this.vsh = vsh; //sign the globla virable with the local virable;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTemperature = new javax.swing.JLabel();
        temperatureTxtF = new javax.swing.JTextField();
        lbBldPressure = new javax.swing.JLabel();
        bldPressureTxtF = new javax.swing.JTextField();
        pulseTxtF = new javax.swing.JTextField();
        lbPulse = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        dateTxtF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Create New Vital Sign");

        lbTemperature.setText("Temperature:");

        lbBldPressure.setText("Blood Pressure:");

        lbPulse.setText("Pulse:");

        lbDate.setText("Date:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbBldPressure)
                                .addGap(38, 38, 38)
                                .addComponent(bldPressureTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTemperature)
                                .addGap(38, 38, 38)
                                .addComponent(temperatureTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDate)
                                    .addComponent(lbPulse))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pulseTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(saveBtn)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperature)
                    .addComponent(temperatureTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBldPressure)
                    .addComponent(bldPressureTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPulse)
                    .addComponent(pulseTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate)
                    .addComponent(dateTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        double temperature = Double.parseDouble(temperatureTxtF.getText());
        double bldPressure = Double.parseDouble(bldPressureTxtF.getText());
        int pulse = Integer.parseInt(pulseTxtF.getText());
        String date = dateTxtF.getText();
        VitalSigns v = vsh.addVitals();    //*
        v.setBloodPressure(bldPressure);
        v.setTemprature(temperature);
        v.setPulse(pulse);
        v.setDate(date);
        JOptionPane.showMessageDialog(null, "VitalSigns added successfully");
        
        bldPressureTxtF.setText("");
        dateTxtF.setText("");
        temperatureTxtF.setText("");
        pulseTxtF.setText("");
        

    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bldPressureTxtF;
    private javax.swing.JTextField dateTxtF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBldPressure;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbPulse;
    private javax.swing.JLabel lbTemperature;
    private javax.swing.JTextField pulseTxtF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField temperatureTxtF;
    // End of variables declaration//GEN-END:variables
}
