/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.costumerRole;

import Business.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class ChooseCategoryJPanel extends javax.swing.JPanel {

    private ProductDirectory productDirectory;
    private JPanel userProcessContainerJPanel;
    
    public ChooseCategoryJPanel(ProductDirectory productDirectory, JPanel userProcessContainerJPanel) {
        initComponents();
        this.productDirectory = productDirectory;
        this.userProcessContainerJPanel = userProcessContainerJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        printerBtn = new javax.swing.JButton();
        computerBtn = new javax.swing.JButton();
        hardwareBtn = new javax.swing.JButton();
        softwareBtn = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 36)); // NOI18N
        jLabel2.setText("Choose a Category");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        printerBtn.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 18)); // NOI18N
        printerBtn.setText("Printer");
        printerBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        printerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerBtnActionPerformed(evt);
            }
        });

        computerBtn.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 18)); // NOI18N
        computerBtn.setText("Computer");
        computerBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        computerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerBtnActionPerformed(evt);
            }
        });

        hardwareBtn.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 18)); // NOI18N
        hardwareBtn.setText("Hardware");
        hardwareBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hardwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardwareBtnActionPerformed(evt);
            }
        });

        softwareBtn.setFont(new java.awt.Font("Hiragino Kaku Gothic ProN", 0, 18)); // NOI18N
        softwareBtn.setText("Software");
        softwareBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        softwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softwareBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(computerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hardwareBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(softwareBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(computerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hardwareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(softwareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hardwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardwareBtnActionPerformed
        String categoryName = hardwareBtn.getText();
        ViewProductJPanel viewProductJPanel = new ViewProductJPanel(productDirectory, userProcessContainerJPanel, categoryName);
        userProcessContainerJPanel.add("viewProductJPanel", viewProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }//GEN-LAST:event_hardwareBtnActionPerformed

    private void softwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softwareBtnActionPerformed
        String categoryName = softwareBtn.getText();
        ViewProductJPanel viewProductJPanel = new ViewProductJPanel(productDirectory, userProcessContainerJPanel, categoryName);
        userProcessContainerJPanel.add("viewProductJPanel", viewProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }//GEN-LAST:event_softwareBtnActionPerformed

    private void computerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerBtnActionPerformed
        String categoryName = computerBtn.getText();
        ViewProductJPanel viewProductJPanel = new ViewProductJPanel(productDirectory, userProcessContainerJPanel, categoryName);
        userProcessContainerJPanel.add("viewProductJPanel", viewProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }//GEN-LAST:event_computerBtnActionPerformed

    private void printerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerBtnActionPerformed
        String categoryName = printerBtn.getText();
        ViewProductJPanel viewProductJPanel = new ViewProductJPanel(productDirectory, userProcessContainerJPanel, categoryName);
        userProcessContainerJPanel.add("viewProductJPanel", viewProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }//GEN-LAST:event_printerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computerBtn;
    private javax.swing.JButton hardwareBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton printerBtn;
    private javax.swing.JButton softwareBtn;
    // End of variables declaration//GEN-END:variables
}
